<link rel="stylesheet" href="<?= $wwwUrl ?>/css/utilities.css">
<link rel="stylesheet" href="<?= $wwwUrl ?>/css/home/home.css">
<link rel="stylesheet" href="<?= $wwwUrl ?>/css/users/admin.css">
<link rel="stylesheet" href="<?= $wwwUrl ?>/css/admin/admin.css">
<main class="container">
  <a class="comeBack" href="<?= $requestUrl ?>/users/admin"><i class="fas fa-arrow-circle-left"></i></a>
  <div style="height:730px; overflow:auto;">
    <table class="tableCoke">
      <tbody>
        <tr class="titleCoke">
          <td>Nom</td>
          <td>Description</td>
          <td>Saison</td>
          <td>Action</td>
        </tr>
        <?php foreach ($episodes as $episode) : ?>
          <tr>
            <td class="nCoke"><?= $episode['Caption'] ?></td>
            <td class="nCoke"><?= $episode['Description'] ?></td>
            <td class="nCoke"><?= $episode['Saison'] ?></td>
            <td class="aCoke">
              <a href="<?= $requestUrl ?>/users/admin/streaming/update?streamingId=<?= $episode['Id'] ?>&artworkId=<?= $episode['Artworks_Id'] ?>&season=<?= $episode['Season_Url'] ?>"><i class="fas fa-pen"></i></a>
              <a href="<?= $requestUrl ?>/users/admin/streaming/delete?streamingId=<?= $episode['Id'] ?>&artworkId=<?= $episode['Artworks_Id'] ?>"><i class="fas fa-trash"></i></a>
            </td>
          </tr>
        <?php endforeach; ?>
      </tbody>
    </table>
  </div>
</main>