<link rel="stylesheet" href="<?= $wwwUrl ?>/css/home/home.css">
<link rel="stylesheet" href="<?= $wwwUrl ?>/css/home/homeStyle.css">
<link rel="stylesheet" href="<?= $wwwUrl ?>/css/home/fontHome.css">
<link rel="stylesheet" href="<?= $wwwUrl ?>/css/users/admin.css">
<link rel="stylesheet" href="<?= $wwwUrl ?>/css/admin/admin.css">
  <main class="container">

    <a class="comeBack" href="<?= $requestUrl ?>/users/admin"><i class="fas fa-arrow-circle-left"></i></a>
    <table class="tableCoke">
      <tbody>
        <tr class="titleCoke">
          <td>Nom</td>
          <td>Description</td>
          <td>Saison</td>
          <td>Action</td>
        </tr>
        <?php foreach ($streamings as $streaming):?>
          <tr>
            <td class="nCoke"><?=$streaming['Caption']?></td>
            <td class="nCoke"><?=$streaming['Description']?></td>
            <td class="nCoke"><?= $streaming['Saison'] ?></td>
            <td class="aCoke">
              <a href="<?= $requestUrl ?>/users/admin/streaming/update?streamingId=<?= $streaming['Id'] ?>&artworkId=<?= $streaming['Artworks_Id'] ?>&specifie=<?= $streaming['Specifie_Url'] ?>"><i class="fas fa-pen"></i></a>
              <a href="<?= $requestUrl ?>/users/admin/streaming/delete?streamingId=<?= $streaming['Id'] ?>&artworkId=<?= $streaming['Artworks_Id'] ?>"><i class="fas fa-trash"></i></a>
            </td>
          </tr>
        <?php endforeach;?>
      </tbody>
    </table>
  </main>
