<link rel="stylesheet" href="<?= $wwwUrl ?>/css/utilities.css">
<link rel="stylesheet" href="<?= $wwwUrl ?>/css/home/home.css">
<link rel="stylesheet" href="<?= $wwwUrl ?>/css/basket/basket.css">
<main class="container">
  <h3>Votre panier !</h3>
  <h4>Récapitulatif de la commande</h4>

  <div id="displayBasket">
    <table class="basketTable">
      <thead>
        <tr>
          <th>Quantité</th>
          <th>Nom</th>
          <th class="desktop">Prix Unitaire</th>
          <th>Prix Total</th>
          <th>Action</th>
        </tr>
      </thead>
      <tfoot>
        <tr>
          <td>Prix Total</td>
          <td></td>
          <td class="desktop"></td>
          <td class="totalPrice"><span id="totalPrice"></span> €</td>
          <td></td>
        </tr>
      </tfoot>
      <tbody>
        <tr></tr>
      </tbody>
    </table>
  </div>
  <?php if (array_key_exists('pseudo', $_SESSION)) { ?>
    <form class="p-form" action="<?= $requestUrl ?>/payment" method="POST">
      <input type="hidden" name="basketItem" id="basketItem" value="">
      <input type="submit" value="Payer ma commande">
    </form>
  <?php } else { ?>
    <p>Vous devez vous <a href="<?= $requestUrl ?>/users/login">connecter</a> afin de pouvoir accéder à cette fonctionnalité.</p>
  <?php } ?>

</main>