<link rel="stylesheet" href="<?= $wwwUrl ?>/css/utilities.css">
<link rel="stylesheet" href="<?= $wwwUrl ?>/css/home/home.css">
<header class="header-main">
  <?php if (array_key_exists('role', $_SESSION) === true) { ?>
    <h4 class="inner-w3layouts-wrap" style="color:white;">Heureux de vous revoir sur notre site,<br> <?= $_SESSION['pseudo'] ?></h4>
  <?php } ?>
</header>
<main>
  <section id="content1" class="inner-w3layouts-wrap">
    <h2>Qu'est-ce que notre site apporte ?</h2>
    <p>Vous vous dîtes surement : "ah encore un pseudo site de streaming qui paraît gratuit mais qui va me ruiner au final, il en vaut surement pas la peine", et bien vous n'avez pas totalement tort. Mais contrairement aux autres sites, on connait les galères de la pauvreté, et pour cela en plus du streaming, nous vous proposons un site exclusif de streaming mélangé à de la vente divers de produits dérivés, et pour pas cher en plus ! Enjoy.</p>
  </section>

</main>