<link rel="stylesheet" href="<?= $wwwUrl ?>/css/utilities.css">
<link rel="stylesheet" href="<?= $wwwUrl ?>/css/home/home.css">
<link rel="stylesheet" href="<?= $wwwUrl ?>/css/users/admin.css">
<link rel="stylesheet" href="<?= $wwwUrl ?>/css/users/update.css">
<main class="container">
    <h3 style="text-align: center;">Modifiez la saison !</h3>
    <a class="comeBack" href="<?= $requestUrl ?>/users/admin/season"><i class="fas fa-arrow-circle-left"></i></a>
    <form class="b-form" action="<?= $requestUrl ?>/users/admin/season/update" method="POST" enctype="multipart/form-data">
        <input type="text" name="name" placeholder="<?= $oeuvre['Season_Name'] ?>" value="<?= $oeuvre['Season_Name'] ?>">
        <input type="text" name="url" placeholder="<?= $oeuvre['Season_Url'] ?>" value="<?= $oeuvre['Season_Url'] ?>">
        <input type="file" name="cover_pics">
        <input type="hidden" name="season" value="<?= $oeuvre['Id'] ?>">
        <input type="submit" name="Enregister">
    </form>
</main>