<link rel="stylesheet" href="<?= $wwwUrl ?>/css/streaming/streaming.css">
<link rel="stylesheet" href="<?= $wwwUrl ?>/css/streaming/streamingStyle.css">
<link rel="stylesheet" href="<?= $wwwUrl ?>/css/streaming/artwork/artwork.css">

  <main class="container">
    <div class="episode-list">
      <?php if (empty($streamings) === false) {
      foreach ($streamings as $streaming) { ?>
        <div class="episode-detail">
          <a href="<?= $requestUrl ?>/streaming/artwork/episode?artworkId=<?= $streaming['ArtworkId'] ?>&status=<?= $streaming['Status'] ?>&id=<?= $streaming['Id'] ?>"><?= $streaming['Caption'] ?>
            <img src="<?= $wwwUrl ?>/ressources/images/cover/<?= $streaming['Image_Cover'] ?>" alt="">
            En ligne le <?= $streaming['CreationTimestamp'] ?></a>
        </div>
      <?php }}else{ ?>
        <p>Il n'y a aucun épisode pour le moment...</p>
      <?php } ?>
    </div>
  </main>