<link rel="stylesheet" href="<?= $wwwUrl ?>/css/streaming/streaming.css">
<link rel="stylesheet" href="<?= $wwwUrl ?>/css/streaming/streamingStyle.css">
<link rel="stylesheet" href="<?= $wwwUrl ?>/css/streaming/artwork/artwork.css">

<main class="container">
  <h2 class="title-section"><?= $title['Name'] ?></h2>
  <form class="search-form" action="<?= $requestUrl ?>/streaming/search" method="post">
    <input type="search" name="search" id="search" placeholder="Recherchez votre film, série, anime...">
    <button type="submit" name="envoi"><i class="fas fa-search"></i></button>
  </form>
  <div class="display-vid">
    <?php foreach ($seasons as $season) : ?>
      <div class="banner-vid">
        <a href="<?= $requestUrl ?>/streaming/artwork/seasons?name=<?= $season['Url'] ?>&artworkId=<?= $season['Id'] ?>&season=<?= $season['Season_Url'] ?>"><img src="<?= $wwwUrl ?>/ressources/images/saisons/<?= $season['Season_Image'] ?>" alt="">
          <?php if (strpos($season['Season_Name'], $season['Name']) === false) { ?>
            <?php if (strlen($season['Name'] . $season['Season_Name']) >= 40) { ?>
              <p style="text-transform: capitalize"><?= substr($season['Name'] . ' ' . $season['Season_Name'], 0, 40) ?>...</p>
            <?php } else { ?>
              <p style="text-transform: capitalize"><?= $season['Name'] . ' ' . $season['Season_Name'] ?></p>
            <?php }
          } else { ?>
            <p style="text-transform: capitalize"><?= substr($season['Season_Name'], 0, 40) ?></p>
          <?php } ?>
        </a>
      </div>
    <?php endforeach; ?>
  </div>
</main>
<script type="text/javascript" src="<?= $wwwUrl ?>/js/search.js"></script>