<link rel="stylesheet" href="<?= $wwwUrl ?>/css/streaming/streaming.css">
<link rel="stylesheet" href="<?= $wwwUrl ?>/css/streaming/streamingStyle.css">
<link rel="stylesheet" href="<?= $wwwUrl ?>/css/streaming/artwork/artwork.css">

<main class="container">
    <?php if (strpos($title['Specifie_Name'], $title['Name']) === false) { ?>
        <h2 class="title-section"><?= $title['Name'] . ' ' . $title['Specifie_Name'] ?></h2>
    <?php } else { ?>
        <h2 class="title-section"><?= $title['Specifie_Name'] ?></h2>
    <?php } ?>
    <div class="episode-list">
        <?php if (empty($specifies) === false) {
            foreach ($specifies as $specifie) { ?>
                <div class="episode-detail">
                    <a href="<?= $requestUrl ?>/streaming/artwork/specifies/episode?artworkId=<?= $specifie['ArtworkId'] ?>&specifie=<?= $specifie['Specifie_Url'] ?>&status=<?= $specifie['Status'] ?>&id=<?= $specifie['Id'] ?>"><?= $specifie['Caption'] ?>
                        <img src="<?= $wwwUrl ?>/ressources/images/cover/<?= $specifie['Image_Cover'] ?>" alt="">
                        En ligne le <?= $specifie['CreationTimestamp'] ?></a>
                </div>
            <?php }
        } else { ?>
            <p>Il n'y a aucun épisode pour le moment...</p>
        <?php } ?>
    </div>
</main>