<link rel="stylesheet" href="<?= $wwwUrl ?>/css/utilities.css">
<link rel="stylesheet" href="<?= $wwwUrl ?>/css/home/home.css">
<link rel="stylesheet" href="<?= $wwwUrl ?>/css/users/user.css">
<?php if ($error != null) { ?>
  <small style="color: red; margin-left:370px; font-style: italic;"><?= $error ?></small>
<?php } ?>
<main class="container">

  <div class="login-right">
    <h3>Connectez-vous !</h3>
    <form class="b-form" action="login" method="POST">
      <div class="sign-in">
        <h4>Email :</h4>
        <input type="text" name="email" placeholder="email">
      </div>
      <div class="sign-in">
        <h4>Password :</h4>
        <input type="password" name="password" placeholder="password">
      </div>
      <div class="sign-in">
        <input type="submit" value="Connexion">
        <p>Vous n'avez pas encore de compte ? Enregistrez-vous <a href="<?= $requestUrl ?>/users/register">ici !</a></p>
      </div>
    </form>
  </div>
</main>