<link rel="stylesheet" href="<?= $wwwUrl ?>/css/utilities.css">
<link rel="stylesheet" href="<?= $wwwUrl ?>/css/home/home.css">
<link rel="stylesheet" href="<?= $wwwUrl ?>/css/users/admin.css">
<link rel="stylesheet" href="<?= $wwwUrl ?>/css/admin/admin.css">
<main class="container">
    <a class="comeBack" href="<?= $requestUrl ?>/users/admin"><i class="fas fa-arrow-circle-left"></i></a>
    <div style="height:730px; overflow:auto;">
        <table class="tableArtwork">
            <tbody>
                <tr class="titleCoke">
                    <td>Nom</td>
                    <td>Url</td>
                    <td>Image</td>
                    <td>Artwork</td>
                    <td>Action</td>
                </tr>
                <?php foreach ($seasons as $season) : ?>
                    <tr>
                        <td class="nCoke"><?= $season['Season_Name'] ?></td>
                        <td class="nCoke"><?= $season['Season_Url'] ?></td>
                        <td class="nCoke"><img src="<?= $wwwUrl ?>/ressources/images/saisons/<?= $season['Season_Image'] ?>" alt=""></td>
                        <td class="nCoke"><?= $season['Artwork_Name'] ?></td>
                        <td class="aCoke">
                            <a href="<?= $requestUrl ?>/users/admin/season/update?season=<?= $season['Id'] ?>"><i class="fas fa-pen"></i></a>
                            <a href="<?= $requestUrl ?>/users/admin/season/delete?season=<?= $season['Id'] ?>"><i class="fas fa-trash"></i></a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</main>