<link rel="stylesheet" href="<?= $wwwUrl ?>/css/home/home.css">
<link rel="stylesheet" href="<?= $wwwUrl ?>/css/home/homeStyle.css">
<link rel="stylesheet" href="<?= $wwwUrl ?>/css/home/fontHome.css">
<link rel="stylesheet" type="text/css" href="<?= $wwwUrl ?>/css/payment/payment.css">
<main class="container">
  <h3>Bien vu, votre paiement a été accepté !</h3>
  <p>Félicitation votre commande <span>n° <?= $user ?> </span>a été enregistrée !</p>
  <a class="back" href="<?= $requestUrl ?>"><i class="fas fa-arrow-circle-left"></i> Retour vers l'accueil</a>
  <img src="http://24.media.tumblr.com/ec0fd88066a9c2aeaf52b51b34436c11/tumblr_n59kgnV9yx1smtaoko2_500.gif" alt="sucess gif">
</main>