<link rel="stylesheet" href="<?= $wwwUrl ?>/css/home/home.css">
<link rel="stylesheet" href="<?= $wwwUrl ?>/css/home/homeStyle.css">
<link rel="stylesheet" href="<?= $wwwUrl ?>/css/home/fontHome.css">
<link rel="stylesheet" href="<?= $wwwUrl ?>/css/users/admin.css">
<link rel="stylesheet" href="<?= $wwwUrl ?>/css/users/update.css">


  <main class="container">

    <h3 style="text-align:center">Ajoutez une oeuvre !</h3>

    <a class="comeBack" href="<?= $requestUrl ?>/users/admin"><i class="fas fa-arrow-circle-left"></i></a>

    <form class="b-form" action="<?= $requestUrl ?>/users/admin/artwork/add" method="post" enctype="multipart/form-data">
        <input type="text" name="name" placeholder="Nom de l'oeuvre">
        <input type="text" name="url" placeholder="Url de l'oeuvre">
        <input type="file" name="artwork_pics">
        <input type="file" name="cover_pics">
          <input type="submit" name="Enregister">
    </form>
  </main>
