<link rel="stylesheet" href="<?= $wwwUrl ?>/css/streaming/streaming.css">
<link rel="stylesheet" href="<?= $wwwUrl ?>/css/streaming/streamingStyle.css">

<main class="container">
  <h2 class="title-section">Tous nos streamings</h2>
  <form class="search-form" action="<?= $requestUrl ?>/streaming/search" method="post">
    <input type="search" name="search" id="search" placeholder="Recherchez votre film, série, anime...">
    <button type="submit" name="envoi"><i class="fas fa-search"></i></button>
  </form>
    <div class="display-vid">
    <?php foreach ($artworkStreams as $artworkStream): ?>
      <div class="banner-vid">
        <a href="<?= $requestUrl ?>/streaming/artwork?name=<?= $artworkStream['Url'] ?>"><img src="<?= $wwwUrl ?>/ressources/images/cover/<?= $artworkStream['Image'] ?>" alt="">
      <p style="text-transform: capitalize"><?= $artworkStream['Name'] ?></p></a>
    </div>
    <?php endforeach; ?>
  </div>
</main>
<script type="text/javascript" src="<?= $wwwUrl ?>/js/search.js"></script>
