<link rel="stylesheet" href="<?= $wwwUrl ?>/css/home/home.css">
<link rel="stylesheet" href="<?= $wwwUrl ?>/css/home/homeStyle.css">
<link rel="stylesheet" href="<?= $wwwUrl ?>/css/home/fontHome.css">
<link rel="stylesheet" href="<?= $wwwUrl ?>/css/products/products.css">

<main class="container">
  <h2 class="title-section">Tous nos produits !</h2>
  <div class="search-bar">
    <form class="search-form" action="<?= $requestUrl ?>/products/search" method="post">
      <input type="search" name="search" placeholder="Recherchez votre film, série, anime...">
      <button type="submit" name="envoi"><i class="fas fa-search"></i></button>
    </form>
  </div>
  <div class="products">
    <ul class="list">
      <?php foreach ($products as $product) { ?>
        <li class="product-mosaic">
          <a href="<?= $requestUrl ?>/products/detail?productId=<?= $product['Id'] ?>">
            <div>
              <?php if (strlen($product['Name']) >= 20) { ?>
                <h3><?= substr($product['Name'], 0, 20) ?> ...</h3>
              <?php } else { ?>
                <h3><?= $product['Name'] ?></h3>
              <?php } ?>
              <img src="<?= $wwwUrl ?>/ressources/images/products/<?= $product['Photo'] ?>">
              <p><?= substr($product['Description'], 0, 30) ?> ...</p>
            </div>
          </a>
          <form>
            <input type="text" name="quantity" id="product-<?= $product['Id'] ?>">
            <button class="addToBasket" data-name="<?= $product['Name'] ?>" data-price="<?= $product['Price'] ?>" data-id="<?= $product['Id'] ?>">
              <p>Ajouter au panier</p>
            </button>
          </form>
        </li>
      <?php } ?>
    </ul>
    <ul class="lines">
      <h4>Toutes les catégories:</h4>
      <?php foreach ($lines as $line) { ?>
        <li class="product-lines">
          <a href="<?= $requestUrl ?>/products/product?name=<?= $line['ProductLine'] ?>"><?= ucfirst($line['ProductLine']) ?>
        </li>
      <?php } ?>
    </ul>
  </div>
</main>