<link rel="stylesheet" href="<?= $wwwUrl ?>/css/home/home.css">
<link rel="stylesheet" href="<?= $wwwUrl ?>/css/home/homeStyle.css">
<link rel="stylesheet" href="<?= $wwwUrl ?>/css/home/fontHome.css">
<link rel="stylesheet" href="<?= $wwwUrl ?>/css/users/admin.css">
<link rel="stylesheet" href="<?= $wwwUrl ?>/css/users/update.css">


  <main class="container">

    <h3 style="text-align:center">Ajoutez une nouvelle video !</h3>

    <a class="comeBack" href="<?= $requestUrl ?>/users/admin"><i class="fas fa-arrow-circle-left"></i></a>

    <form class="b-form" action="<?= $requestUrl ?>/users/admin/streaming/add" method="post" enctype="multipart/form-data">
        <input type="text" name="caption" placeholder="Nom de la video">
        <input type="file" accept=".mp4" name="vid_pics">
        <input type="text" name="artworksId" placeholder="Id du artwork">
        <textarea type="text" name="description" maxlength="1000"></textarea>
        <input type="text" name="status" placeholder="N° de l'episode">
          <input type="submit" name="Enregister">
    </form>
  </main>
