<link rel="stylesheet" href="<?= $wwwUrl ?>/css/home/home.css">
<link rel="stylesheet" href="<?= $wwwUrl ?>/css/home/homeStyle.css">
<link rel="stylesheet" href="<?= $wwwUrl ?>/css/home/fontHome.css">
<link rel="stylesheet" href="<?= $wwwUrl ?>/css/users/admin.css">
<link rel="stylesheet" href="<?= $wwwUrl ?>/css/admin/admin.css">

<main class="container">

    <a class="comeBack" href="<?= $requestUrl ?>/users/admin"><i class="fas fa-arrow-circle-left"></i></a>
    <table class="tableArtwork">
        <tbody>
            <tr class="titleCoke">
                <td>Nom</td>
                <td>Url</td>
                <td>Image</td>
                <td>Artwork</td>
                <td>Action</td>
            </tr>
            <?php foreach ($specifies as $specifie) : ?>
                <tr>
                    <td class="nCoke"><?= $specifie['Specifie_Name'] ?></td>
                    <td class="nCoke"><?= $specifie['Specifie_Url'] ?></td>
                    <td class="nCoke"><img src="<?= $wwwUrl ?>/ressources/images/saisons/<?= $specifie['Specifie_Image'] ?>" alt=""></td>
                    <td class="nCoke"><?= $specifie['Artwork_Name'] ?></td>
                    <td class="aCoke">
                        <a href="<?= $requestUrl ?>/users/admin/specifie/update?specifie=<?= $specifie['Id'] ?>"><i class="fas fa-pen"></i></a>
                        <a href="<?= $requestUrl ?>/users/admin/specifie/delete?specifie=<?= $specifie['Id'] ?>"><i class="fas fa-trash"></i></a>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</main>