<link rel="stylesheet" href="<?= $wwwUrl ?>/css/utilities.css">
<link rel="stylesheet" href="<?= $wwwUrl ?>/css/home/home.css">
<link rel="stylesheet" href="<?= $wwwUrl ?>/css/users/user.css">
<main class="container" style="width: 40%;">
  <?php if ($error != null) { ?>
    <small style="color: red; margin-left:370px; font-style: italic;"><?= $error ?></small>
  <?php } ?>
  <div class="login-bottom">
    <h3>Enregistrez vous !</h3>
    <form class="b-form" action="Register" method="POST">
      <div class="sign-up">
        <h4>Votre prénom :</h4>
        <input type="text" name="firstname" placeholder="Prénom">
      </div>
      <div class="sign-up">
        <h4>Votre nom :</h4>
        <input type="text" name="lastname" placeholder="Nom">
      </div>
      <div class="sign-up">
        <h4>Votre pseudo :</h4>
        <input type="text" name="pseudo" placeholder="Pseudo">
      </div>
      <div class="sign-up">
        <h4>Email :</h4>
        <input type="text" name="email" placeholder="Email">
      </div>
      <div class="sign-up">
        <h4>Password :</h4>
        <input type="password" name="password" placeholder="Mot de passe">

      </div>
      <div class="sign-up">
        <h4>Adresse :</h4>
        <input type="text" name="address" placeholder="Adresse">

      </div>
      <div class="sign-up">
        <h4>Ville :</h4>
        <input type="text" name="city" placeholder="Ville">

      </div>
      <div class="sign-up">
        <h4>Code postal :</h4>
        <input type="text" name="zip" placeholder="Code postal">

      </div>
      <div class="sign-up">
        <input type="submit" value="REGISTER NOW">
      </div>

    </form>
  </div>
</main>