<link rel="stylesheet" href="<?= $wwwUrl ?>/css/home/home.css">
<link rel="stylesheet" href="<?= $wwwUrl ?>/css/home/homeStyle.css">
<link rel="stylesheet" href="<?= $wwwUrl ?>/css/home/fontHome.css">
<link rel="stylesheet" href="<?= $wwwUrl ?>/css/products/products.css">
<link rel="stylesheet" href="<?= $wwwUrl ?>/css/products/detail/detail.css">

<main class="container">
  <a class="comeBack" href="<?= $requestUrl ?>/products?start=0"><i class="fas fa-arrow-circle-left"></i></a>
  <div class="productDetail">
    <img src="<?= $wwwUrl ?>/ressources/images/products/<?= $product['Photo'] ?>">
    <h3><?= $product['productName'] ?></h3>
    <p><?= $product['Description'] ?></p>
    <div class="paymentPart">
      <span>Prix Unitaire : <em><?= $product['Price'] ?> €</em></span>
      <form>
        <input type="number" name="quantity" id="product-<?= $product['ProductId'] ?>">
        <button class="addToBasket" data-name="<?= $product['productName'] ?>" data-price="<?= $product['Price'] ?>" data-id="<?= $product['ProductId'] ?>">
          <p>Ajouter au panier</p>
        </button>
      </form>
    </div>
    <section class="espace-com">
      <h4>Espace commentaire</h4>
      <div class="show-post">
        <?php for ($i = 0; $i < count($posts); $i++) { ?>
          <div class="post">
            <h5 class="title-post"><?= $posts[$i]['Nickname'] ?></h5>
            <p><?= $posts[$i]['Content'] ?></p>
            <small><em>Le <?= date('d/m/Y à H:m:s', strtotime($posts[$i]['CreationTimestamp'])) ?></em></small>
            <hr class="separation">
          </div>
        <?php } ?>
      </div>
      <?php if (array_key_exists('pseudo', $_SESSION)) { ?>
        <form class="form-post" action="<?= $requestUrl ?>/products/detail?productId=<?= $product['ProductId'] ?>" method="post">
          <textarea name="post" rows="4" cols="80" placeholder="Ecrire un nouveau commentaire"></textarea>
          <input type="hidden" name="productId" value="<?= $product['ProductId'] ?>">
          <button type="submit" name="envoyer">Envoyer</button>
        </form>
      <?php } else { ?>
        <p>Vous devez vous <a href="<?= $requestUrl ?>/users/login">connecter</a> afin de pouvoir poster un commentaire.</p>
      <?php } ?>
    </section>
  </div>
</main>