<link rel="stylesheet" href="<?= $wwwUrl ?>/css/home/home.css">
<link rel="stylesheet" href="<?= $wwwUrl ?>/css/home/homeStyle.css">
<link rel="stylesheet" href="<?= $wwwUrl ?>/css/home/fontHome.css">
<link rel="stylesheet" href="<?= $wwwUrl ?>/css/users/admin.css">
<link rel="stylesheet" href="<?= $wwwUrl ?>/css/users/update.css">

<main class="container">

    <h3 style="text-align: center;">Modifiez la saison !</h3>

    <a class="comeBack" href="<?= $requestUrl ?>/users/admin/specifie"><i class="fas fa-arrow-circle-left"></i></a>

    <form class="b-form" action="<?= $requestUrl ?>/users/admin/specifie/update" method="POST" enctype="multipart/form-data">
        <input type="text" name="name" placeholder="<?= $oeuvre['Specifie_Name'] ?>" value="<?= $oeuvre['Specifie_Name'] ?>">
        <input type="text" name="url" placeholder="<?= $oeuvre['Specifie_Url'] ?>" value="<?= $oeuvre['Specifie_Url'] ?>">
        <input type="file" name="cover_pics">
        <input type="hidden" name="specifie" value="<?= $oeuvre['Id'] ?>">
        <input type="submit" name="Enregister">
    </form>
</main>