<link rel="stylesheet" href="<?= $wwwUrl ?>/css/home/home.css">
<link rel="stylesheet" href="<?= $wwwUrl ?>/css/home/homeStyle.css">
<link rel="stylesheet" href="<?= $wwwUrl ?>/css/home/fontHome.css">
<link rel="stylesheet" href="<?= $wwwUrl ?>/css/users/admin.css">
<link rel="stylesheet" href="<?= $wwwUrl ?>/css/users/update.css">

  <main class="container">

    <h3 style="text-align:center;" >Ajoutez un nouveau produit !</h3>

    <a class="comeBack" href="<?= $requestUrl ?>/users/admin"><i class="fas fa-arrow-circle-left"></i></a>

    <form class="b-form" action="<?= $requestUrl ?>/users/admin/product/add" method="POST" enctype="multipart/form-data">
      <input type="text" name="name" placeholder="Nom du produit">
      <input type="file" name="product_pics">
      <input type="text" name="artworksId" placeholder="Id du artwork">
      <select type="text" name="productline">
        <?php foreach ($lines as $line): ?>
          <option value="<?= $line['ProductLine'] ?>"><?= $line['ProductLine'] ?></option>
        <?php endforeach; ?>
      </select>
      <textarea type="text" name="description" maxlength="1000"></textarea>
      <input type="text" name="quantity" placeholder="Quantité">
      <input type="text" name="buyPrice" placeholder="Prix de d'achat">
      <input type="text" name="price" placeholder="Prix de vente">
      <input type="submit" name="Enregister">
    </form>
  </main>
