<link rel="stylesheet" href="<?= $wwwUrl ?>/css/home/home.css">
<link rel="stylesheet" href="<?= $wwwUrl ?>/css/home/homeStyle.css">
<link rel="stylesheet" href="<?= $wwwUrl ?>/css/home/fontHome.css">
<link rel="stylesheet" href="<?= $wwwUrl ?>/css/users/admin.css">
<link rel="stylesheet" href="<?= $wwwUrl ?>/css/users/update.css">


  <main class="container">

    <h3 style="text-align: center;">Modifiez le produit !</h3>

    <a class="comeBack" href="<?= $requestUrl ?>/users/admin/product"><i class="fas fa-arrow-circle-left"></i></a>

    <form class="b-form" action="<?= $requestUrl ?>/users/admin/product/update" method="POST" enctype="multipart/form-data">
      <input type="text" name="name" placeholder="<?= $product['Name'] ?>" value="<?= $product['Name'] ?>">
      <input type="file" name="product_pics">
      <input type="text" name="artworksId" placeholder="<?= $product['Artworks_Id'] ?>" value="<?= $product['Artworks_Id'] ?>">
      <select type="text" name="productline">
        <option value="<?= $product['ProductLine'] ?>" selected><?= $product['ProductLine'] ?></option>
        <?php foreach ($lines as $line): ?>
          <option value="<?= $line['ProductLine'] ?>"><?= $line['ProductLine'] ?></option>
        <?php endforeach; ?>
      </select>
      <textarea type="text" name="description" maxlength="1000"><?= $product['Description'] ?></textarea>
      <input type="text" name="quantity" placeholder="<?= $product['QuantityInStock'] ?>" value="<?= $product['QuantityInStock'] ?>">
      <input type="text" name="buyPrice" placeholder="<?= $product['BuyPrice'] ?>" value="<?= $product['BuyPrice'] ?>">
      <input type="text" name="price" placeholder="<?= $product['Price'] ?>" value="<?= $product['Price'] ?>">
      <input type="hidden" name="productId" value="<?=$product['Id']?>">
      <input type="submit" name="Enregister">
    </form>
  </main>
